# Generated by Django 5.2.6 on 2025-09-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_nome_autor_autor_rename_s_nome_autor_s_autor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='ano',
            new_name='ano_publicacao',
        ),
    ]
