# Generated by Django 5.2.6 on 2025-10-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_ano_livro_ano_publicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagem', models.ImageField(upload_to='upload/%Y%m%d/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
