# Generated by Django 5.2.6 on 2025-10-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_livro_capa_alter_imagem_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='ano_publicacao',
            new_name='ano',
        ),
    ]
